language: ruby
cache: bundler
rvm:
  - 2.1.5
  - ruby-head
bundler_args: --without production
gemfile:
  - Gemfile
addons:
  code_climate:
    repo_token: 232cbe99dfd802bf915eac4bc660c511cba71551f94df8541bd6f25a5f8fca24
notifications:
  email: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test
