language: ruby
cache: bundler
before_install:
  - sed -i '2d' Gemfile
rvm:
  - 2.1.5
bundler_args: "--without production"
services:
  - redis-server
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database dropblog_test;' -U postgres
  - psql -U postgres -q -d dropblog_test -f db/structure.sql
  - cp config/database.travis.yml config/database.yml
script: bundle exec rake
addons:
  code_climate:
    repo_token: 232cbe99dfd802bf915eac4bc660c511cba71551f94df8541bd6f25a5f8fca24
notifications:
  email: false
env:
  secure: gTCOVqHYS1L6j6rq7Gmrm9EuCaBRM2X7MGHba3lpqj1oRZHO/YkFxToDSTPR57BF7N3SJfLLyU2cF90OW2p5JZmSfbsgyIKkNiY2YaZFVHkbaHc02c9W4fuTG2PqB23j3KeCrDYi7JNGayRnTIV99dizTeDJqkwuTc1ywMCqbhw=
  secure: trKrdt+PVZfzjiKgOjUsrbP7eImjK/Zgx8EOXa+3k40MAFolIWFHAqrY6/iFtu4E3UV1TjMM2kGXnCr2X5nryufx/0VHJ1kAXj/C1DTXs6jBmq7jOSaWHAsAzl9+EIjyV8hAD/ZQRvlI8VzfdQvXSFgpLWWejKxb4R48WCgE7Gw=
  secure: R/9Tu/Er2WmlsfMBbIV5okpN90mHk7RSN36K4hIo528y9GoaB4mlFy1fJcfHKKEUNk7vsAVQhWb4P4PsPNqSbD68ODtPPT2B6tlg/r0HPw2qBjIpSodfSVjzog2bDBSzOgGaGxQQDoPqKLIjOrXgBnvs6bTEQJDXywtqsrwf0AQ=
deploy:
  provider: heroku
  api_key:
    secure: 1aWBH2CJ9cSCapxJpqUzkoVisQcVjlCq6hA7sEFWJ8C0ZZplJ0v2CBBjxEZHACdjFAwdkq4zYxmp6jPkidwACCK+MwC8fWO2W4qnvtzOg4MRrMCVSPiYOLYlEEW5LUHFkOkTOQ+wDccQxfd6KuPt24xP+pSeGaltJSjk7gZ0J9g=
  app: neverstopbuilding-dropblog
  on:
    repo: neverstopbuilding/dropblog
  run: "rake db:migrate"
